/*******************************************************************************
 * Copyright (c) 2015 CoolSquid.
 * All rights reserved.
 *******************************************************************************/
package com.github.coolsquid.squidapi;

import com.github.coolsquid.squidapi.util.Utils;

import cpw.mods.fml.common.Loader;
import cpw.mods.fml.common.ModMetadata;

public class SquidAPIMod {
	
	public SquidAPIMod(String desc) {
		ModMetadata meta = Loader.instance().activeModContainer().getMetadata();
		meta.autogenerated = false;
		meta.authorList = Utils.newList("CoolSquid");
		meta.url = "http://coolsquid.wix.com/software";
		meta.description = desc;
		meta.credits = "";
	}
}