/*******************************************************************************
 * Copyright (c) 2015 CoolSquid.
 * All rights reserved.
 *******************************************************************************/
package com.github.coolsquid.squidapi.registry;

import net.minecraft.item.Item;

public final class VanillaItemRegistry extends LockedRegistry<Item> {

	private static final VanillaItemRegistry instance = new VanillaItemRegistry();

	public static VanillaItemRegistry instance() {
		return instance;
	}

	private VanillaItemRegistry() {
		this.register("iron_shovel", (Item) Item.itemRegistry.getObject("minecraft:iron_shovel"));
		this.register("iron_pickaxe", (Item) Item.itemRegistry.getObject("minecraft:iron_pickaxe"));
		this.register("iron_axe", (Item) Item.itemRegistry.getObject("minecraft:iron_axe"));
		this.register("flint_and_steel", (Item) Item.itemRegistry.getObject("minecraft:flint_and_steel"));
		this.register("apple", (Item) Item.itemRegistry.getObject("minecraft:apple"));
		this.register("bow", (Item) Item.itemRegistry.getObject("minecraft:bow"));
		this.register("arrow", (Item) Item.itemRegistry.getObject("minecraft:arrow"));
		this.register("coal", (Item) Item.itemRegistry.getObject("minecraft:coal"));
		this.register("diamond", (Item) Item.itemRegistry.getObject("minecraft:diamond"));
		this.register("iron_ingot", (Item) Item.itemRegistry.getObject("minecraft:iron_ingot"));
		this.register("gold_ingot", (Item) Item.itemRegistry.getObject("minecraft:gold_ingot"));
		this.register("iron_sword", (Item) Item.itemRegistry.getObject("minecraft:iron_sword"));
		this.register("wooden_sword", (Item) Item.itemRegistry.getObject("minecraft:wooden_sword"));
		this.register("wooden_shovel", (Item) Item.itemRegistry.getObject("minecraft:wooden_shovel"));
		this.register("wooden_pickaxe", (Item) Item.itemRegistry.getObject("minecraft:wooden_pickaxe"));
		this.register("wooden_axe", (Item) Item.itemRegistry.getObject("minecraft:wooden_axe"));
		this.register("stone_sword", (Item) Item.itemRegistry.getObject("minecraft:stone_sword"));
		this.register("stone_shovel", (Item) Item.itemRegistry.getObject("minecraft:stone_shovel"));
		this.register("stone_pickaxe", (Item) Item.itemRegistry.getObject("minecraft:stone_pickaxe"));
		this.register("stone_axe", (Item) Item.itemRegistry.getObject("minecraft:stone_axe"));
		this.register("diamond_sword", (Item) Item.itemRegistry.getObject("minecraft:diamond_sword"));
		this.register("diamond_shovel", (Item) Item.itemRegistry.getObject("minecraft:diamond_shovel"));
		this.register("diamond_pickaxe", (Item) Item.itemRegistry.getObject("minecraft:diamond_pickaxe"));
		this.register("diamond_axe", (Item) Item.itemRegistry.getObject("minecraft:diamond_axe"));
		this.register("stick", (Item) Item.itemRegistry.getObject("minecraft:stick"));
		this.register("bowl", (Item) Item.itemRegistry.getObject("minecraft:bowl"));
		this.register("mushroom_stew", (Item) Item.itemRegistry.getObject("minecraft:mushroom_stew"));
		this.register("golden_sword", (Item) Item.itemRegistry.getObject("minecraft:golden_sword"));
		this.register("golden_shovel", (Item) Item.itemRegistry.getObject("minecraft:golden_shovel"));
		this.register("golden_pickaxe", (Item) Item.itemRegistry.getObject("minecraft:golden_pickaxe"));
		this.register("golden_axe", (Item) Item.itemRegistry.getObject("minecraft:golden_axe"));
		this.register("string", (Item) Item.itemRegistry.getObject("minecraft:string"));
		this.register("feather", (Item) Item.itemRegistry.getObject("minecraft:feather"));
		this.register("gunpowder", (Item) Item.itemRegistry.getObject("minecraft:gunpowder"));
		this.register("wooden_hoe", (Item) Item.itemRegistry.getObject("minecraft:wooden_hoe"));
		this.register("stone_hoe", (Item) Item.itemRegistry.getObject("minecraft:stone_hoe"));
		this.register("iron_hoe", (Item) Item.itemRegistry.getObject("minecraft:iron_hoe"));
		this.register("diamond_hoe", (Item) Item.itemRegistry.getObject("minecraft:diamond_hoe"));
		this.register("golden_hoe", (Item) Item.itemRegistry.getObject("minecraft:golden_hoe"));
		this.register("wheat_seeds", (Item) Item.itemRegistry.getObject("minecraft:wheat_seeds"));
		this.register("wheat", (Item) Item.itemRegistry.getObject("minecraft:wheat"));
		this.register("bread", (Item) Item.itemRegistry.getObject("minecraft:bread"));
		this.register("leather_helmet", (Item) Item.itemRegistry.getObject("minecraft:leather_helmet"));
		this.register("leather_chestplate", (Item) Item.itemRegistry.getObject("minecraft:leather_chestplate"));
		this.register("leather_leggings", (Item) Item.itemRegistry.getObject("minecraft:leather_leggings"));
		this.register("leather_boots", (Item) Item.itemRegistry.getObject("minecraft:leather_boots"));
		this.register("chainmail_helmet", (Item) Item.itemRegistry.getObject("minecraft:chainmail_helmet"));
		this.register("chainmail_chestplate", (Item) Item.itemRegistry.getObject("minecraft:chainmail_chestplate"));
		this.register("chainmail_leggings", (Item) Item.itemRegistry.getObject("minecraft:chainmail_leggings"));
		this.register("chainmail_boots", (Item) Item.itemRegistry.getObject("minecraft:chainmail_boots"));
		this.register("iron_helmet", (Item) Item.itemRegistry.getObject("minecraft:iron_helmet"));
		this.register("iron_chestplate", (Item) Item.itemRegistry.getObject("minecraft:iron_chestplate"));
		this.register("iron_leggings", (Item) Item.itemRegistry.getObject("minecraft:iron_leggings"));
		this.register("iron_boots", (Item) Item.itemRegistry.getObject("minecraft:iron_boots"));
		this.register("diamond_helmet", (Item) Item.itemRegistry.getObject("minecraft:diamond_helmet"));
		this.register("diamond_chestplate", (Item) Item.itemRegistry.getObject("minecraft:diamond_chestplate"));
		this.register("diamond_leggings", (Item) Item.itemRegistry.getObject("minecraft:diamond_leggings"));
		this.register("diamond_boots", (Item) Item.itemRegistry.getObject("minecraft:diamond_boots"));
		this.register("golden_helmet", (Item) Item.itemRegistry.getObject("minecraft:golden_helmet"));
		this.register("golden_chestplate", (Item) Item.itemRegistry.getObject("minecraft:golden_chestplate"));
		this.register("golden_leggings", (Item) Item.itemRegistry.getObject("minecraft:golden_leggings"));
		this.register("golden_boots", (Item) Item.itemRegistry.getObject("minecraft:golden_boots"));
		this.register("flint", (Item) Item.itemRegistry.getObject("minecraft:flint"));
		this.register("porkchop", (Item) Item.itemRegistry.getObject("minecraft:porkchop"));
		this.register("cooked_porkchop", (Item) Item.itemRegistry.getObject("minecraft:cooked_porkchop"));
		this.register("painting", (Item) Item.itemRegistry.getObject("minecraft:painting"));
		this.register("golden_apple", (Item) Item.itemRegistry.getObject("minecraft:golden_apple"));
		this.register("sign", (Item) Item.itemRegistry.getObject("minecraft:sign"));
		this.register("wooden_door", (Item) Item.itemRegistry.getObject("minecraft:wooden_door"));
		this.register("bucket", (Item) Item.itemRegistry.getObject("minecraft:bucket"));
		this.register("water_bucket", (Item) Item.itemRegistry.getObject("minecraft:water_bucket"));
		this.register("lava_bucket", (Item) Item.itemRegistry.getObject("minecraft:lava_bucket"));
		this.register("minecart", (Item) Item.itemRegistry.getObject("minecraft:minecart"));
		this.register("saddle", (Item) Item.itemRegistry.getObject("minecraft:saddle"));
		this.register("iron_door", (Item) Item.itemRegistry.getObject("minecraft:iron_door"));
		this.register("redstone", (Item) Item.itemRegistry.getObject("minecraft:redstone"));
		this.register("snowball", (Item) Item.itemRegistry.getObject("minecraft:snowball"));
		this.register("boat", (Item) Item.itemRegistry.getObject("minecraft:boat"));
		this.register("leather", (Item) Item.itemRegistry.getObject("minecraft:leather"));
		this.register("milk_bucket", (Item) Item.itemRegistry.getObject("minecraft:milk_bucket"));
		this.register("brick", (Item) Item.itemRegistry.getObject("minecraft:brick"));
		this.register("clay_ball", (Item) Item.itemRegistry.getObject("minecraft:clay_ball"));
		this.register("reeds", (Item) Item.itemRegistry.getObject("minecraft:reeds"));
		this.register("paper", (Item) Item.itemRegistry.getObject("minecraft:paper"));
		this.register("book", (Item) Item.itemRegistry.getObject("minecraft:book"));
		this.register("slime_ball", (Item) Item.itemRegistry.getObject("minecraft:slime_ball"));
		this.register("chest_minecart", (Item) Item.itemRegistry.getObject("minecraft:chest_minecart"));
		this.register("furnace_minecart", (Item) Item.itemRegistry.getObject("minecraft:furnace_minecart"));
		this.register("egg", (Item) Item.itemRegistry.getObject("minecraft:egg"));
		this.register("compass", (Item) Item.itemRegistry.getObject("minecraft:compass"));
		this.register("fishing_rod", (Item) Item.itemRegistry.getObject("minecraft:fishing_rod"));
		this.register("clock", (Item) Item.itemRegistry.getObject("minecraft:clock"));
		this.register("glowstone_dust", (Item) Item.itemRegistry.getObject("minecraft:glowstone_dust"));
		this.register("fish", (Item) Item.itemRegistry.getObject("minecraft:fish"));
		this.register("cooked_fished", (Item) Item.itemRegistry.getObject("minecraft:cooked_fished"));
		this.register("dye", (Item) Item.itemRegistry.getObject("minecraft:dye"));
		this.register("bone", (Item) Item.itemRegistry.getObject("minecraft:bone"));
		this.register("sugar", (Item) Item.itemRegistry.getObject("minecraft:sugar"));
		this.register("cake", (Item) Item.itemRegistry.getObject("minecraft:cake"));
		this.register("bed", (Item) Item.itemRegistry.getObject("minecraft:bed"));
		this.register("repeater", (Item) Item.itemRegistry.getObject("minecraft:repeater"));
		this.register("cookie", (Item) Item.itemRegistry.getObject("minecraft:cookie"));
		this.register("filled_map", (Item) Item.itemRegistry.getObject("minecraft:filled_map"));
		this.register("shears", (Item) Item.itemRegistry.getObject("minecraft:shears"));
		this.register("melon", (Item) Item.itemRegistry.getObject("minecraft:melon"));
		this.register("pumpkin_seeds", (Item) Item.itemRegistry.getObject("minecraft:pumpkin_seeds"));
		this.register("melon_seeds", (Item) Item.itemRegistry.getObject("minecraft:melon_seeds"));
		this.register("beef", (Item) Item.itemRegistry.getObject("minecraft:beef"));
		this.register("cooked_beef", (Item) Item.itemRegistry.getObject("minecraft:cooked_beef"));
		this.register("chicken", (Item) Item.itemRegistry.getObject("minecraft:chicken"));
		this.register("cooked_chicken", (Item) Item.itemRegistry.getObject("minecraft:cooked_chicken"));
		this.register("rotten_flesh", (Item) Item.itemRegistry.getObject("minecraft:rotten_flesh"));
		this.register("ender_pearl", (Item) Item.itemRegistry.getObject("minecraft:ender_pearl"));
		this.register("blaze_rod", (Item) Item.itemRegistry.getObject("minecraft:blaze_rod"));
		this.register("ghast_tear", (Item) Item.itemRegistry.getObject("minecraft:ghast_tear"));
		this.register("gold_nugget", (Item) Item.itemRegistry.getObject("minecraft:gold_nugget"));
		this.register("nether_wart", (Item) Item.itemRegistry.getObject("minecraft:nether_wart"));
		this.register("potion", (Item) Item.itemRegistry.getObject("minecraft:potion"));
		this.register("glass_bottle", (Item) Item.itemRegistry.getObject("minecraft:glass_bottle"));
		this.register("spider_eye", (Item) Item.itemRegistry.getObject("minecraft:spider_eye"));
		this.register("fermented_spider_eye", (Item) Item.itemRegistry.getObject("minecraft:fermented_spider_eye"));
		this.register("blaze_powder", (Item) Item.itemRegistry.getObject("minecraft:blaze_powder"));
		this.register("magma_cream", (Item) Item.itemRegistry.getObject("minecraft:magma_cream"));
		this.register("brewing_stand", (Item) Item.itemRegistry.getObject("minecraft:brewing_stand"));
		this.register("cauldron", (Item) Item.itemRegistry.getObject("minecraft:cauldron"));
		this.register("ender_eye", (Item) Item.itemRegistry.getObject("minecraft:ender_eye"));
		this.register("speckled_melon", (Item) Item.itemRegistry.getObject("minecraft:speckled_melon"));
		this.register("spawn_egg", (Item) Item.itemRegistry.getObject("minecraft:spawn_egg"));
		this.register("experience_bottle", (Item) Item.itemRegistry.getObject("minecraft:experience_bottle"));
		this.register("fire_charge", (Item) Item.itemRegistry.getObject("minecraft:fire_charge"));
		this.register("writable_book", (Item) Item.itemRegistry.getObject("minecraft:writable_book"));
		this.register("written_book", (Item) Item.itemRegistry.getObject("minecraft:written_book"));
		this.register("emerald", (Item) Item.itemRegistry.getObject("minecraft:emerald"));
		this.register("item_frame", (Item) Item.itemRegistry.getObject("minecraft:item_frame"));
		this.register("flower_pot", (Item) Item.itemRegistry.getObject("minecraft:flower_pot"));
		this.register("carrot", (Item) Item.itemRegistry.getObject("minecraft:carrot"));
		this.register("potato", (Item) Item.itemRegistry.getObject("minecraft:potato"));
		this.register("baked_potato", (Item) Item.itemRegistry.getObject("minecraft:baked_potato"));
		this.register("poisonous_potato", (Item) Item.itemRegistry.getObject("minecraft:poisonous_potato"));
		this.register("map", (Item) Item.itemRegistry.getObject("minecraft:map"));
		this.register("golden_carrot", (Item) Item.itemRegistry.getObject("minecraft:golden_carrot"));
		this.register("skull", (Item) Item.itemRegistry.getObject("minecraft:skull"));
		this.register("carrot_on_a_stick", (Item) Item.itemRegistry.getObject("minecraft:carrot_on_a_stick"));
		this.register("nether_star", (Item) Item.itemRegistry.getObject("minecraft:nether_star"));
		this.register("pumpkin_pie", (Item) Item.itemRegistry.getObject("minecraft:pumpkin_pie"));
		this.register("fireworks", (Item) Item.itemRegistry.getObject("minecraft:fireworks"));
		this.register("firework_charge", (Item) Item.itemRegistry.getObject("minecraft:firework_charge"));
		this.register("enchanted_book", (Item) Item.itemRegistry.getObject("minecraft:enchanted_book"));
		this.register("comparator", (Item) Item.itemRegistry.getObject("minecraft:comparator"));
		this.register("netherbrick", (Item) Item.itemRegistry.getObject("minecraft:netherbrick"));
		this.register("quartz", (Item) Item.itemRegistry.getObject("minecraft:quartz"));
		this.register("tnt_minecart", (Item) Item.itemRegistry.getObject("minecraft:tnt_minecart"));
		this.register("hopper_minecart", (Item) Item.itemRegistry.getObject("minecraft:hopper_minecart"));
		this.register("iron_horse_armor", (Item) Item.itemRegistry.getObject("minecraft:iron_horse_armor"));
		this.register("golden_horse_armor", (Item) Item.itemRegistry.getObject("minecraft:golden_horse_armor"));
		this.register("diamond_horse_armor", (Item) Item.itemRegistry.getObject("minecraft:diamond_horse_armor"));
		this.register("lead", (Item) Item.itemRegistry.getObject("minecraft:lead"));
		this.register("name_tag", (Item) Item.itemRegistry.getObject("minecraft:name_tag"));
		this.register("command_block_minecart", (Item) Item.itemRegistry.getObject("minecraft:command_block_minecart"));
		this.register("record_13", (Item) Item.itemRegistry.getObject("minecraft:record_13"));
		this.register("record_cat", (Item) Item.itemRegistry.getObject("minecraft:record_cat"));
		this.register("record_blocks", (Item) Item.itemRegistry.getObject("minecraft:record_blocks"));
		this.register("record_chirp", (Item) Item.itemRegistry.getObject("minecraft:record_chirp"));
		this.register("record_far", (Item) Item.itemRegistry.getObject("minecraft:record_far"));
		this.register("record_mall", (Item) Item.itemRegistry.getObject("minecraft:record_mall"));
		this.register("record_mellohi", (Item) Item.itemRegistry.getObject("minecraft:record_mellohi"));
		this.register("record_stal", (Item) Item.itemRegistry.getObject("minecraft:record_stal"));
		this.register("record_strad", (Item) Item.itemRegistry.getObject("minecraft:record_strad"));
		this.register("record_ward", (Item) Item.itemRegistry.getObject("minecraft:record_ward"));
		this.register("record_11", (Item) Item.itemRegistry.getObject("minecraft:record_11"));
		this.register("record_wait", (Item) Item.itemRegistry.getObject("minecraft:record_wait"));
		
		this.lock();
	}
}