/*******************************************************************************
 * Copyright (c) 2015 CoolSquid.
 * All rights reserved.
 *******************************************************************************/
package com.github.coolsquid.squidapi.registry;

import net.minecraft.block.Block;

public class VanillaBlockRegistry extends Registry<Block> {
	
	private static final VanillaBlockRegistry instance = new VanillaBlockRegistry();
	
	public static VanillaBlockRegistry instance() {
		return instance;
	}

	public VanillaBlockRegistry() {
		this.register("minecraft:air", (Block) Block.blockRegistry.getObject("minecraft:air"));
		this.register("minecraft:stone", (Block) Block.blockRegistry.getObject("minecraft:stone"));
		this.register("minecraft:grass", (Block) Block.blockRegistry.getObject("minecraft:grass"));
		this.register("minecraft:dirt", (Block) Block.blockRegistry.getObject("minecraft:dirt"));
		this.register("minecraft:cobblestone", (Block) Block.blockRegistry.getObject("minecraft:cobblestone"));
		this.register("minecraft:planks", (Block) Block.blockRegistry.getObject("minecraft:planks"));
		this.register("minecraft:sapling", (Block) Block.blockRegistry.getObject("minecraft:sapling"));
		this.register("minecraft:bedrock", (Block) Block.blockRegistry.getObject("minecraft:bedrock"));
		this.register("minecraft:flowing_water", (Block) Block.blockRegistry.getObject("minecraft:flowing_water"));
		this.register("minecraft:water", (Block) Block.blockRegistry.getObject("minecraft:water"));
		this.register("minecraft:flowing_lava", (Block) Block.blockRegistry.getObject("minecraft:flowing_lava"));
		this.register("minecraft:lava", (Block) Block.blockRegistry.getObject("minecraft:lava"));
		this.register("minecraft:sand", (Block) Block.blockRegistry.getObject("minecraft:sand"));
		this.register("minecraft:gravel", (Block) Block.blockRegistry.getObject("minecraft:gravel"));
		this.register("minecraft:gold_ore", (Block) Block.blockRegistry.getObject("minecraft:gold_ore"));
		this.register("minecraft:iron_ore", (Block) Block.blockRegistry.getObject("minecraft:iron_ore"));
		this.register("minecraft:coal_ore", (Block) Block.blockRegistry.getObject("minecraft:coal_ore"));
		this.register("minecraft:log", (Block) Block.blockRegistry.getObject("minecraft:log"));
		this.register("minecraft:leaves", (Block) Block.blockRegistry.getObject("minecraft:leaves"));
		this.register("minecraft:sponge", (Block) Block.blockRegistry.getObject("minecraft:sponge"));
		this.register("minecraft:glass", (Block) Block.blockRegistry.getObject("minecraft:glass"));
		this.register("minecraft:lapis_ore", (Block) Block.blockRegistry.getObject("minecraft:lapis_ore"));
		this.register("minecraft:lapis_block", (Block) Block.blockRegistry.getObject("minecraft:lapis_block"));
		this.register("minecraft:dispenser", (Block) Block.blockRegistry.getObject("minecraft:dispenser"));
		this.register("minecraft:sandstone", (Block) Block.blockRegistry.getObject("minecraft:sandstone"));
		this.register("minecraft:noteblock", (Block) Block.blockRegistry.getObject("minecraft:noteblock"));
		this.register("minecraft:bed", (Block) Block.blockRegistry.getObject("minecraft:bed"));
		this.register("minecraft:golden_rail", (Block) Block.blockRegistry.getObject("minecraft:golden_rail"));
		this.register("minecraft:detector_rail", (Block) Block.blockRegistry.getObject("minecraft:detector_rail"));
		this.register("minecraft:sticky_piston", (Block) Block.blockRegistry.getObject("minecraft:sticky_piston"));
		this.register("minecraft:web", (Block) Block.blockRegistry.getObject("minecraft:web"));
		this.register("minecraft:tallgrass", (Block) Block.blockRegistry.getObject("minecraft:tallgrass"));
		this.register("minecraft:deadbush", (Block) Block.blockRegistry.getObject("minecraft:deadbush"));
		this.register("minecraft:piston", (Block) Block.blockRegistry.getObject("minecraft:piston"));
		this.register("minecraft:piston_head", (Block) Block.blockRegistry.getObject("minecraft:piston_head"));
		this.register("minecraft:wool", (Block) Block.blockRegistry.getObject("minecraft:wool"));
		this.register("minecraft:piston_extension", (Block) Block.blockRegistry.getObject("minecraft:piston_extension"));
		this.register("minecraft:yellow_flower", (Block) Block.blockRegistry.getObject("minecraft:yellow_flower"));
		this.register("minecraft:red_flower", (Block) Block.blockRegistry.getObject("minecraft:red_flower"));
		this.register("minecraft:brown_mushroom", (Block) Block.blockRegistry.getObject("minecraft:brown_mushroom"));
		this.register("minecraft:red_mushroom", (Block) Block.blockRegistry.getObject("minecraft:red_mushroom"));
		this.register("minecraft:gold_block", (Block) Block.blockRegistry.getObject("minecraft:gold_block"));
		this.register("minecraft:iron_block", (Block) Block.blockRegistry.getObject("minecraft:iron_block"));
		this.register("minecraft:double_stone_slab", (Block) Block.blockRegistry.getObject("minecraft:double_stone_slab"));
		this.register("minecraft:stone_slab", (Block) Block.blockRegistry.getObject("minecraft:stone_slab"));
		this.register("minecraft:brick_block", (Block) Block.blockRegistry.getObject("minecraft:brick_block"));
		this.register("minecraft:tnt", (Block) Block.blockRegistry.getObject("minecraft:tnt"));
		this.register("minecraft:bookshelf", (Block) Block.blockRegistry.getObject("minecraft:bookshelf"));
		this.register("minecraft:mossy_cobblestone", (Block) Block.blockRegistry.getObject("minecraft:mossy_cobblestone"));
		this.register("minecraft:obsidian", (Block) Block.blockRegistry.getObject("minecraft:obsidian"));
		this.register("minecraft:torch", (Block) Block.blockRegistry.getObject("minecraft:torch"));
		this.register("minecraft:fire", (Block) Block.blockRegistry.getObject("minecraft:fire"));
		this.register("minecraft:mob_spawner", (Block) Block.blockRegistry.getObject("minecraft:mob_spawner"));
		this.register("minecraft:oak_stairs", (Block) Block.blockRegistry.getObject("minecraft:oak_stairs"));
		this.register("minecraft:chest", (Block) Block.blockRegistry.getObject("minecraft:chest"));
		this.register("minecraft:redstone_wire", (Block) Block.blockRegistry.getObject("minecraft:redstone_wire"));
		this.register("minecraft:diamond_ore", (Block) Block.blockRegistry.getObject("minecraft:diamond_ore"));
		this.register("minecraft:diamond_block", (Block) Block.blockRegistry.getObject("minecraft:diamond_block"));
		this.register("minecraft:crafting_table", (Block) Block.blockRegistry.getObject("minecraft:crafting_table"));
		this.register("minecraft:wheat", (Block) Block.blockRegistry.getObject("minecraft:wheat"));
		this.register("minecraft:farmland", (Block) Block.blockRegistry.getObject("minecraft:farmland"));
		this.register("minecraft:furnace", (Block) Block.blockRegistry.getObject("minecraft:furnace"));
		this.register("minecraft:lit_furnace", (Block) Block.blockRegistry.getObject("minecraft:lit_furnace"));
		this.register("minecraft:standing_sign", (Block) Block.blockRegistry.getObject("minecraft:standing_sign"));
		this.register("minecraft:wooden_door", (Block) Block.blockRegistry.getObject("minecraft:wooden_door"));
		this.register("minecraft:ladder", (Block) Block.blockRegistry.getObject("minecraft:ladder"));
		this.register("minecraft:rail", (Block) Block.blockRegistry.getObject("minecraft:rail"));
		this.register("minecraft:stone_stairs", (Block) Block.blockRegistry.getObject("minecraft:stone_stairs"));
		this.register("minecraft:wall_sign", (Block) Block.blockRegistry.getObject("minecraft:wall_sign"));
		this.register("minecraft:lever", (Block) Block.blockRegistry.getObject("minecraft:lever"));
		this.register("minecraft:stone_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:stone_pressure_plate"));
		this.register("minecraft:iron_door", (Block) Block.blockRegistry.getObject("minecraft:iron_door"));
		this.register("minecraft:wooden_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:wooden_pressure_plate"));
		this.register("minecraft:redstone_ore", (Block) Block.blockRegistry.getObject("minecraft:redstone_ore"));
		this.register("minecraft:lit_redstone_ore", (Block) Block.blockRegistry.getObject("minecraft:lit_redstone_ore"));
		this.register("minecraft:unlit_redstone_torch", (Block) Block.blockRegistry.getObject("minecraft:unlit_redstone_torch"));
		this.register("minecraft:redstone_torch", (Block) Block.blockRegistry.getObject("minecraft:redstone_torch"));
		this.register("minecraft:stone_button", (Block) Block.blockRegistry.getObject("minecraft:stone_button"));
		this.register("minecraft:snow_layer", (Block) Block.blockRegistry.getObject("minecraft:snow_layer"));
		this.register("minecraft:ice", (Block) Block.blockRegistry.getObject("minecraft:ice"));
		this.register("minecraft:snow", (Block) Block.blockRegistry.getObject("minecraft:snow"));
		this.register("minecraft:cactus", (Block) Block.blockRegistry.getObject("minecraft:cactus"));
		this.register("minecraft:clay", (Block) Block.blockRegistry.getObject("minecraft:clay"));
		this.register("minecraft:reeds", (Block) Block.blockRegistry.getObject("minecraft:reeds"));
		this.register("minecraft:jukebox", (Block) Block.blockRegistry.getObject("minecraft:jukebox"));
		this.register("minecraft:fence", (Block) Block.blockRegistry.getObject("minecraft:fence"));
		this.register("minecraft:pumpkin", (Block) Block.blockRegistry.getObject("minecraft:pumpkin"));
		this.register("minecraft:netherrack", (Block) Block.blockRegistry.getObject("minecraft:netherrack"));
		this.register("minecraft:soul_sand", (Block) Block.blockRegistry.getObject("minecraft:soul_sand"));
		this.register("minecraft:glowstone", (Block) Block.blockRegistry.getObject("minecraft:glowstone"));
		this.register("minecraft:portal", (Block) Block.blockRegistry.getObject("minecraft:portal"));
		this.register("minecraft:lit_pumpkin", (Block) Block.blockRegistry.getObject("minecraft:lit_pumpkin"));
		this.register("minecraft:cake", (Block) Block.blockRegistry.getObject("minecraft:cake"));
		this.register("minecraft:unpowered_repeater", (Block) Block.blockRegistry.getObject("minecraft:unpowered_repeater"));
		this.register("minecraft:powered_repeater", (Block) Block.blockRegistry.getObject("minecraft:powered_repeater"));
		this.register("minecraft:stained_glass", (Block) Block.blockRegistry.getObject("minecraft:stained_glass"));
		this.register("minecraft:trapdoor", (Block) Block.blockRegistry.getObject("minecraft:trapdoor"));
		this.register("minecraft:monster_egg", (Block) Block.blockRegistry.getObject("minecraft:monster_egg"));
		this.register("minecraft:stonebrick", (Block) Block.blockRegistry.getObject("minecraft:stonebrick"));
		this.register("minecraft:brown_mushroom_block", (Block) Block.blockRegistry.getObject("minecraft:brown_mushroom_block"));
		this.register("minecraft:red_mushroom_block", (Block) Block.blockRegistry.getObject("minecraft:red_mushroom_block"));
		this.register("minecraft:iron_bars", (Block) Block.blockRegistry.getObject("minecraft:iron_bars"));
		this.register("minecraft:glass_pane", (Block) Block.blockRegistry.getObject("minecraft:glass_pane"));
		this.register("minecraft:melon_block", (Block) Block.blockRegistry.getObject("minecraft:melon_block"));
		this.register("minecraft:pumpkin_stem", (Block) Block.blockRegistry.getObject("minecraft:pumpkin_stem"));
		this.register("minecraft:melon_stem", (Block) Block.blockRegistry.getObject("minecraft:melon_stem"));
		this.register("minecraft:vine", (Block) Block.blockRegistry.getObject("minecraft:vine"));
		this.register("minecraft:fence_gate", (Block) Block.blockRegistry.getObject("minecraft:fence_gate"));
		this.register("minecraft:brick_stairs", (Block) Block.blockRegistry.getObject("minecraft:brick_stairs"));
		this.register("minecraft:stone_brick_stairs", (Block) Block.blockRegistry.getObject("minecraft:stone_brick_stairs"));
		this.register("minecraft:mycelium", (Block) Block.blockRegistry.getObject("minecraft:mycelium"));
		this.register("minecraft:waterlily", (Block) Block.blockRegistry.getObject("minecraft:waterlily"));
		this.register("minecraft:nether_brick", (Block) Block.blockRegistry.getObject("minecraft:nether_brick"));
		this.register("minecraft:nether_brick_fence", (Block) Block.blockRegistry.getObject("minecraft:nether_brick_fence"));
		this.register("minecraft:nether_brick_stairs", (Block) Block.blockRegistry.getObject("minecraft:nether_brick_stairs"));
		this.register("minecraft:nether_wart", (Block) Block.blockRegistry.getObject("minecraft:nether_wart"));
		this.register("minecraft:enchanting_table", (Block) Block.blockRegistry.getObject("minecraft:enchanting_table"));
		this.register("minecraft:brewing_stand", (Block) Block.blockRegistry.getObject("minecraft:brewing_stand"));
		this.register("minecraft:cauldron", (Block) Block.blockRegistry.getObject("minecraft:cauldron"));
		this.register("minecraft:end_portal", (Block) Block.blockRegistry.getObject("minecraft:end_portal"));
		this.register("minecraft:end_portal_frame", (Block) Block.blockRegistry.getObject("minecraft:end_portal_frame"));
		this.register("minecraft:end_stone", (Block) Block.blockRegistry.getObject("minecraft:end_stone"));
		this.register("minecraft:dragon_egg", (Block) Block.blockRegistry.getObject("minecraft:dragon_egg"));
		this.register("minecraft:redstone_lamp", (Block) Block.blockRegistry.getObject("minecraft:redstone_lamp"));
		this.register("minecraft:lit_redstone_lamp", (Block) Block.blockRegistry.getObject("minecraft:lit_redstone_lamp"));
		this.register("minecraft:double_wooden_slab", (Block) Block.blockRegistry.getObject("minecraft:double_wooden_slab"));
		this.register("minecraft:wooden_slab", (Block) Block.blockRegistry.getObject("minecraft:wooden_slab"));
		this.register("minecraft:cocoa", (Block) Block.blockRegistry.getObject("minecraft:cocoa"));
		this.register("minecraft:sandstone_stairs", (Block) Block.blockRegistry.getObject("minecraft:sandstone_stairs"));
		this.register("minecraft:emerald_ore", (Block) Block.blockRegistry.getObject("minecraft:emerald_ore"));
		this.register("minecraft:ender_chest", (Block) Block.blockRegistry.getObject("minecraft:ender_chest"));
		this.register("minecraft:tripwire_hook", (Block) Block.blockRegistry.getObject("minecraft:tripwire_hook"));
		this.register("minecraft:tripwire", (Block) Block.blockRegistry.getObject("minecraft:tripwire"));
		this.register("minecraft:emerald_block", (Block) Block.blockRegistry.getObject("minecraft:emerald_block"));
		this.register("minecraft:spruce_stairs", (Block) Block.blockRegistry.getObject("minecraft:spruce_stairs"));
		this.register("minecraft:birch_stairs", (Block) Block.blockRegistry.getObject("minecraft:birch_stairs"));
		this.register("minecraft:jungle_stairs", (Block) Block.blockRegistry.getObject("minecraft:jungle_stairs"));
		this.register("minecraft:command_block", (Block) Block.blockRegistry.getObject("minecraft:command_block"));
		this.register("minecraft:beacon", (Block) Block.blockRegistry.getObject("minecraft:beacon"));
		this.register("minecraft:cobblestone_wall", (Block) Block.blockRegistry.getObject("minecraft:cobblestone_wall"));
		this.register("minecraft:flower_pot", (Block) Block.blockRegistry.getObject("minecraft:flower_pot"));
		this.register("minecraft:carrots", (Block) Block.blockRegistry.getObject("minecraft:carrots"));
		this.register("minecraft:potatoes", (Block) Block.blockRegistry.getObject("minecraft:potatoes"));
		this.register("minecraft:wooden_button", (Block) Block.blockRegistry.getObject("minecraft:wooden_button"));
		this.register("minecraft:skull", (Block) Block.blockRegistry.getObject("minecraft:skull"));
		this.register("minecraft:anvil", (Block) Block.blockRegistry.getObject("minecraft:anvil"));
		this.register("minecraft:trapped_chest", (Block) Block.blockRegistry.getObject("minecraft:trapped_chest"));
		this.register("minecraft:light_weighted_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:light_weighted_pressure_plate"));
		this.register("minecraft:heavy_weighted_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:heavy_weighted_pressure_plate"));
		this.register("minecraft:unpowered_comparator", (Block) Block.blockRegistry.getObject("minecraft:unpowered_comparator"));
		this.register("minecraft:powered_comparator", (Block) Block.blockRegistry.getObject("minecraft:powered_comparator"));
		this.register("minecraft:daylight_detector", (Block) Block.blockRegistry.getObject("minecraft:daylight_detector"));
		this.register("minecraft:redstone_block", (Block) Block.blockRegistry.getObject("minecraft:redstone_block"));
		this.register("minecraft:quartz_ore", (Block) Block.blockRegistry.getObject("minecraft:quartz_ore"));
		this.register("minecraft:hopper", (Block) Block.blockRegistry.getObject("minecraft:hopper"));
		this.register("minecraft:quartz_block", (Block) Block.blockRegistry.getObject("minecraft:quartz_block"));
		this.register("minecraft:quartz_stairs", (Block) Block.blockRegistry.getObject("minecraft:quartz_stairs"));
		this.register("minecraft:activator_rail", (Block) Block.blockRegistry.getObject("minecraft:activator_rail"));
		this.register("minecraft:dropper", (Block) Block.blockRegistry.getObject("minecraft:dropper"));
		this.register("minecraft:stained_hardened_clay", (Block) Block.blockRegistry.getObject("minecraft:stained_hardened_clay"));
		this.register("minecraft:stained_glass_pane", (Block) Block.blockRegistry.getObject("minecraft:stained_glass_pane"));
		this.register("minecraft:leaves2", (Block) Block.blockRegistry.getObject("minecraft:leaves2"));
		this.register("minecraft:log2", (Block) Block.blockRegistry.getObject("minecraft:log2"));
		this.register("minecraft:acacia_stairs", (Block) Block.blockRegistry.getObject("minecraft:acacia_stairs"));
		this.register("minecraft:dark_oak_stairs", (Block) Block.blockRegistry.getObject("minecraft:dark_oak_stairs"));
		this.register("minecraft:hay_block", (Block) Block.blockRegistry.getObject("minecraft:hay_block"));
		this.register("minecraft:carpet", (Block) Block.blockRegistry.getObject("minecraft:carpet"));
		this.register("minecraft:hardened_clay", (Block) Block.blockRegistry.getObject("minecraft:hardened_clay"));
		this.register("minecraft:coal_block", (Block) Block.blockRegistry.getObject("minecraft:coal_block"));
		this.register("minecraft:packed_ice", (Block) Block.blockRegistry.getObject("minecraft:packed_ice"));
		this.register("minecraft:double_plant", (Block) Block.blockRegistry.getObject("minecraft:double_plant"));

	}
}