/*******************************************************************************
 * Copyright (c) 2015 CoolSquid.
 * All rights reserved.
 *******************************************************************************/
package com.github.coolsquid.squidapi.registry;

import net.minecraft.block.Block;

public final class VanillaBlockRegistry extends LockedRegistry<Block> {

	private static final VanillaBlockRegistry instance = new VanillaBlockRegistry();

	public static VanillaBlockRegistry instance() {
		return instance;
	}

	private VanillaBlockRegistry() {
		this.register("air", (Block) Block.blockRegistry.getObject("minecraft:air"));
		this.register("stone", (Block) Block.blockRegistry.getObject("minecraft:stone"));
		this.register("grass", (Block) Block.blockRegistry.getObject("minecraft:grass"));
		this.register("dirt", (Block) Block.blockRegistry.getObject("minecraft:dirt"));
		this.register("cobblestone", (Block) Block.blockRegistry.getObject("minecraft:cobblestone"));
		this.register("planks", (Block) Block.blockRegistry.getObject("minecraft:planks"));
		this.register("sapling", (Block) Block.blockRegistry.getObject("minecraft:sapling"));
		this.register("bedrock", (Block) Block.blockRegistry.getObject("minecraft:bedrock"));
		this.register("flowing_water", (Block) Block.blockRegistry.getObject("minecraft:flowing_water"));
		this.register("water", (Block) Block.blockRegistry.getObject("minecraft:water"));
		this.register("flowing_lava", (Block) Block.blockRegistry.getObject("minecraft:flowing_lava"));
		this.register("lava", (Block) Block.blockRegistry.getObject("minecraft:lava"));
		this.register("sand", (Block) Block.blockRegistry.getObject("minecraft:sand"));
		this.register("gravel", (Block) Block.blockRegistry.getObject("minecraft:gravel"));
		this.register("gold_ore", (Block) Block.blockRegistry.getObject("minecraft:gold_ore"));
		this.register("iron_ore", (Block) Block.blockRegistry.getObject("minecraft:iron_ore"));
		this.register("coal_ore", (Block) Block.blockRegistry.getObject("minecraft:coal_ore"));
		this.register("log", (Block) Block.blockRegistry.getObject("minecraft:log"));
		this.register("leaves", (Block) Block.blockRegistry.getObject("minecraft:leaves"));
		this.register("sponge", (Block) Block.blockRegistry.getObject("minecraft:sponge"));
		this.register("glass", (Block) Block.blockRegistry.getObject("minecraft:glass"));
		this.register("lapis_ore", (Block) Block.blockRegistry.getObject("minecraft:lapis_ore"));
		this.register("lapis_block", (Block) Block.blockRegistry.getObject("minecraft:lapis_block"));
		this.register("dispenser", (Block) Block.blockRegistry.getObject("minecraft:dispenser"));
		this.register("sandstone", (Block) Block.blockRegistry.getObject("minecraft:sandstone"));
		this.register("noteblock", (Block) Block.blockRegistry.getObject("minecraft:noteblock"));
		this.register("bed", (Block) Block.blockRegistry.getObject("minecraft:bed"));
		this.register("golden_rail", (Block) Block.blockRegistry.getObject("minecraft:golden_rail"));
		this.register("detector_rail", (Block) Block.blockRegistry.getObject("minecraft:detector_rail"));
		this.register("sticky_piston", (Block) Block.blockRegistry.getObject("minecraft:sticky_piston"));
		this.register("web", (Block) Block.blockRegistry.getObject("minecraft:web"));
		this.register("tallgrass", (Block) Block.blockRegistry.getObject("minecraft:tallgrass"));
		this.register("deadbush", (Block) Block.blockRegistry.getObject("minecraft:deadbush"));
		this.register("piston", (Block) Block.blockRegistry.getObject("minecraft:piston"));
		this.register("piston_head", (Block) Block.blockRegistry.getObject("minecraft:piston_head"));
		this.register("wool", (Block) Block.blockRegistry.getObject("minecraft:wool"));
		this.register("piston_extension", (Block) Block.blockRegistry.getObject("minecraft:piston_extension"));
		this.register("yellow_flower", (Block) Block.blockRegistry.getObject("minecraft:yellow_flower"));
		this.register("red_flower", (Block) Block.blockRegistry.getObject("minecraft:red_flower"));
		this.register("brown_mushroom", (Block) Block.blockRegistry.getObject("minecraft:brown_mushroom"));
		this.register("red_mushroom", (Block) Block.blockRegistry.getObject("minecraft:red_mushroom"));
		this.register("gold_block", (Block) Block.blockRegistry.getObject("minecraft:gold_block"));
		this.register("iron_block", (Block) Block.blockRegistry.getObject("minecraft:iron_block"));
		this.register("double_stone_slab", (Block) Block.blockRegistry.getObject("minecraft:double_stone_slab"));
		this.register("stone_slab", (Block) Block.blockRegistry.getObject("minecraft:stone_slab"));
		this.register("brick_block", (Block) Block.blockRegistry.getObject("minecraft:brick_block"));
		this.register("tnt", (Block) Block.blockRegistry.getObject("minecraft:tnt"));
		this.register("bookshelf", (Block) Block.blockRegistry.getObject("minecraft:bookshelf"));
		this.register("mossy_cobblestone", (Block) Block.blockRegistry.getObject("minecraft:mossy_cobblestone"));
		this.register("obsidian", (Block) Block.blockRegistry.getObject("minecraft:obsidian"));
		this.register("torch", (Block) Block.blockRegistry.getObject("minecraft:torch"));
		this.register("fire", (Block) Block.blockRegistry.getObject("minecraft:fire"));
		this.register("mob_spawner", (Block) Block.blockRegistry.getObject("minecraft:mob_spawner"));
		this.register("oak_stairs", (Block) Block.blockRegistry.getObject("minecraft:oak_stairs"));
		this.register("chest", (Block) Block.blockRegistry.getObject("minecraft:chest"));
		this.register("redstone_wire", (Block) Block.blockRegistry.getObject("minecraft:redstone_wire"));
		this.register("diamond_ore", (Block) Block.blockRegistry.getObject("minecraft:diamond_ore"));
		this.register("diamond_block", (Block) Block.blockRegistry.getObject("minecraft:diamond_block"));
		this.register("crafting_table", (Block) Block.blockRegistry.getObject("minecraft:crafting_table"));
		this.register("wheat", (Block) Block.blockRegistry.getObject("minecraft:wheat"));
		this.register("farmland", (Block) Block.blockRegistry.getObject("minecraft:farmland"));
		this.register("furnace", (Block) Block.blockRegistry.getObject("minecraft:furnace"));
		this.register("lit_furnace", (Block) Block.blockRegistry.getObject("minecraft:lit_furnace"));
		this.register("standing_sign", (Block) Block.blockRegistry.getObject("minecraft:standing_sign"));
		this.register("wooden_door", (Block) Block.blockRegistry.getObject("minecraft:wooden_door"));
		this.register("ladder", (Block) Block.blockRegistry.getObject("minecraft:ladder"));
		this.register("rail", (Block) Block.blockRegistry.getObject("minecraft:rail"));
		this.register("stone_stairs", (Block) Block.blockRegistry.getObject("minecraft:stone_stairs"));
		this.register("wall_sign", (Block) Block.blockRegistry.getObject("minecraft:wall_sign"));
		this.register("lever", (Block) Block.blockRegistry.getObject("minecraft:lever"));
		this.register("stone_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:stone_pressure_plate"));
		this.register("iron_door", (Block) Block.blockRegistry.getObject("minecraft:iron_door"));
		this.register("wooden_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:wooden_pressure_plate"));
		this.register("redstone_ore", (Block) Block.blockRegistry.getObject("minecraft:redstone_ore"));
		this.register("lit_redstone_ore", (Block) Block.blockRegistry.getObject("minecraft:lit_redstone_ore"));
		this.register("unlit_redstone_torch", (Block) Block.blockRegistry.getObject("minecraft:unlit_redstone_torch"));
		this.register("redstone_torch", (Block) Block.blockRegistry.getObject("minecraft:redstone_torch"));
		this.register("stone_button", (Block) Block.blockRegistry.getObject("minecraft:stone_button"));
		this.register("snow_layer", (Block) Block.blockRegistry.getObject("minecraft:snow_layer"));
		this.register("ice", (Block) Block.blockRegistry.getObject("minecraft:ice"));
		this.register("snow", (Block) Block.blockRegistry.getObject("minecraft:snow"));
		this.register("cactus", (Block) Block.blockRegistry.getObject("minecraft:cactus"));
		this.register("clay", (Block) Block.blockRegistry.getObject("minecraft:clay"));
		this.register("reeds", (Block) Block.blockRegistry.getObject("minecraft:reeds"));
		this.register("jukebox", (Block) Block.blockRegistry.getObject("minecraft:jukebox"));
		this.register("fence", (Block) Block.blockRegistry.getObject("minecraft:fence"));
		this.register("pumpkin", (Block) Block.blockRegistry.getObject("minecraft:pumpkin"));
		this.register("netherrack", (Block) Block.blockRegistry.getObject("minecraft:netherrack"));
		this.register("soul_sand", (Block) Block.blockRegistry.getObject("minecraft:soul_sand"));
		this.register("glowstone", (Block) Block.blockRegistry.getObject("minecraft:glowstone"));
		this.register("portal", (Block) Block.blockRegistry.getObject("minecraft:portal"));
		this.register("lit_pumpkin", (Block) Block.blockRegistry.getObject("minecraft:lit_pumpkin"));
		this.register("cake", (Block) Block.blockRegistry.getObject("minecraft:cake"));
		this.register("unpowered_repeater", (Block) Block.blockRegistry.getObject("minecraft:unpowered_repeater"));
		this.register("powered_repeater", (Block) Block.blockRegistry.getObject("minecraft:powered_repeater"));
		this.register("stained_glass", (Block) Block.blockRegistry.getObject("minecraft:stained_glass"));
		this.register("trapdoor", (Block) Block.blockRegistry.getObject("minecraft:trapdoor"));
		this.register("monster_egg", (Block) Block.blockRegistry.getObject("minecraft:monster_egg"));
		this.register("stonebrick", (Block) Block.blockRegistry.getObject("minecraft:stonebrick"));
		this.register("brown_mushroom_block", (Block) Block.blockRegistry.getObject("minecraft:brown_mushroom_block"));
		this.register("red_mushroom_block", (Block) Block.blockRegistry.getObject("minecraft:red_mushroom_block"));
		this.register("iron_bars", (Block) Block.blockRegistry.getObject("minecraft:iron_bars"));
		this.register("glass_pane", (Block) Block.blockRegistry.getObject("minecraft:glass_pane"));
		this.register("melon_block", (Block) Block.blockRegistry.getObject("minecraft:melon_block"));
		this.register("pumpkin_stem", (Block) Block.blockRegistry.getObject("minecraft:pumpkin_stem"));
		this.register("melon_stem", (Block) Block.blockRegistry.getObject("minecraft:melon_stem"));
		this.register("vine", (Block) Block.blockRegistry.getObject("minecraft:vine"));
		this.register("fence_gate", (Block) Block.blockRegistry.getObject("minecraft:fence_gate"));
		this.register("brick_stairs", (Block) Block.blockRegistry.getObject("minecraft:brick_stairs"));
		this.register("stone_brick_stairs", (Block) Block.blockRegistry.getObject("minecraft:stone_brick_stairs"));
		this.register("mycelium", (Block) Block.blockRegistry.getObject("minecraft:mycelium"));
		this.register("waterlily", (Block) Block.blockRegistry.getObject("minecraft:waterlily"));
		this.register("nether_brick", (Block) Block.blockRegistry.getObject("minecraft:nether_brick"));
		this.register("nether_brick_fence", (Block) Block.blockRegistry.getObject("minecraft:nether_brick_fence"));
		this.register("nether_brick_stairs", (Block) Block.blockRegistry.getObject("minecraft:nether_brick_stairs"));
		this.register("nether_wart", (Block) Block.blockRegistry.getObject("minecraft:nether_wart"));
		this.register("enchanting_table", (Block) Block.blockRegistry.getObject("minecraft:enchanting_table"));
		this.register("brewing_stand", (Block) Block.blockRegistry.getObject("minecraft:brewing_stand"));
		this.register("cauldron", (Block) Block.blockRegistry.getObject("minecraft:cauldron"));
		this.register("end_portal", (Block) Block.blockRegistry.getObject("minecraft:end_portal"));
		this.register("end_portal_frame", (Block) Block.blockRegistry.getObject("minecraft:end_portal_frame"));
		this.register("end_stone", (Block) Block.blockRegistry.getObject("minecraft:end_stone"));
		this.register("dragon_egg", (Block) Block.blockRegistry.getObject("minecraft:dragon_egg"));
		this.register("redstone_lamp", (Block) Block.blockRegistry.getObject("minecraft:redstone_lamp"));
		this.register("lit_redstone_lamp", (Block) Block.blockRegistry.getObject("minecraft:lit_redstone_lamp"));
		this.register("double_wooden_slab", (Block) Block.blockRegistry.getObject("minecraft:double_wooden_slab"));
		this.register("wooden_slab", (Block) Block.blockRegistry.getObject("minecraft:wooden_slab"));
		this.register("cocoa", (Block) Block.blockRegistry.getObject("minecraft:cocoa"));
		this.register("sandstone_stairs", (Block) Block.blockRegistry.getObject("minecraft:sandstone_stairs"));
		this.register("emerald_ore", (Block) Block.blockRegistry.getObject("minecraft:emerald_ore"));
		this.register("ender_chest", (Block) Block.blockRegistry.getObject("minecraft:ender_chest"));
		this.register("tripwire_hook", (Block) Block.blockRegistry.getObject("minecraft:tripwire_hook"));
		this.register("tripwire", (Block) Block.blockRegistry.getObject("minecraft:tripwire"));
		this.register("emerald_block", (Block) Block.blockRegistry.getObject("minecraft:emerald_block"));
		this.register("spruce_stairs", (Block) Block.blockRegistry.getObject("minecraft:spruce_stairs"));
		this.register("birch_stairs", (Block) Block.blockRegistry.getObject("minecraft:birch_stairs"));
		this.register("jungle_stairs", (Block) Block.blockRegistry.getObject("minecraft:jungle_stairs"));
		this.register("command_block", (Block) Block.blockRegistry.getObject("minecraft:command_block"));
		this.register("beacon", (Block) Block.blockRegistry.getObject("minecraft:beacon"));
		this.register("cobblestone_wall", (Block) Block.blockRegistry.getObject("minecraft:cobblestone_wall"));
		this.register("flower_pot", (Block) Block.blockRegistry.getObject("minecraft:flower_pot"));
		this.register("carrots", (Block) Block.blockRegistry.getObject("minecraft:carrots"));
		this.register("potatoes", (Block) Block.blockRegistry.getObject("minecraft:potatoes"));
		this.register("wooden_button", (Block) Block.blockRegistry.getObject("minecraft:wooden_button"));
		this.register("skull", (Block) Block.blockRegistry.getObject("minecraft:skull"));
		this.register("anvil", (Block) Block.blockRegistry.getObject("minecraft:anvil"));
		this.register("trapped_chest", (Block) Block.blockRegistry.getObject("minecraft:trapped_chest"));
		this.register("light_weighted_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:light_weighted_pressure_plate"));
		this.register("heavy_weighted_pressure_plate", (Block) Block.blockRegistry.getObject("minecraft:heavy_weighted_pressure_plate"));
		this.register("unpowered_comparator", (Block) Block.blockRegistry.getObject("minecraft:unpowered_comparator"));
		this.register("powered_comparator", (Block) Block.blockRegistry.getObject("minecraft:powered_comparator"));
		this.register("daylight_detector", (Block) Block.blockRegistry.getObject("minecraft:daylight_detector"));
		this.register("redstone_block", (Block) Block.blockRegistry.getObject("minecraft:redstone_block"));
		this.register("quartz_ore", (Block) Block.blockRegistry.getObject("minecraft:quartz_ore"));
		this.register("hopper", (Block) Block.blockRegistry.getObject("minecraft:hopper"));
		this.register("quartz_block", (Block) Block.blockRegistry.getObject("minecraft:quartz_block"));
		this.register("quartz_stairs", (Block) Block.blockRegistry.getObject("minecraft:quartz_stairs"));
		this.register("activator_rail", (Block) Block.blockRegistry.getObject("minecraft:activator_rail"));
		this.register("dropper", (Block) Block.blockRegistry.getObject("minecraft:dropper"));
		this.register("stained_hardened_clay", (Block) Block.blockRegistry.getObject("minecraft:stained_hardened_clay"));
		this.register("stained_glass_pane", (Block) Block.blockRegistry.getObject("minecraft:stained_glass_pane"));
		this.register("leaves2", (Block) Block.blockRegistry.getObject("minecraft:leaves2"));
		this.register("log2", (Block) Block.blockRegistry.getObject("minecraft:log2"));
		this.register("acacia_stairs", (Block) Block.blockRegistry.getObject("minecraft:acacia_stairs"));
		this.register("dark_oak_stairs", (Block) Block.blockRegistry.getObject("minecraft:dark_oak_stairs"));
		this.register("hay_block", (Block) Block.blockRegistry.getObject("minecraft:hay_block"));
		this.register("carpet", (Block) Block.blockRegistry.getObject("minecraft:carpet"));
		this.register("hardened_clay", (Block) Block.blockRegistry.getObject("minecraft:hardened_clay"));
		this.register("coal_block", (Block) Block.blockRegistry.getObject("minecraft:coal_block"));
		this.register("packed_ice", (Block) Block.blockRegistry.getObject("minecraft:packed_ice"));
		this.register("double_plant", (Block) Block.blockRegistry.getObject("minecraft:double_plant"));

		this.lock();
	}
}